//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyHH
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public int number { get; set; }
        public string status { get; set; }
    }
}
